Get http://localhost:3000
Content-Type: application/json

{
    "email":"eyal"
   
}
###

Post http://localhost:3000
Content-Type: application/json

{
    "email":"eyal"
   
}

###
Get http://localhost:3000/api/user



###
Post http://localhost:3000/api/user
Content-Type: application/json

{
    "email":"menu@gmail.com",
    "password":"menu1",
    "userName":"menu ear",
    "gender":"1"
}

###
Get http://localhost:3000/api/user/eyal Golan


###
Delete http://localhost:3000/api/user/undefined

###
Post http://localhost:3000/api/post
Content-Type: application/json

{
    "posterEmail":"eyal",
    "textPost":"eyal1",
    "urlPath":"1"
}




